twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        catalogs_directory: '%catalogs_directory_path%'

when@test:
    twig:
        strict_variables: true,
        form_themes: ['bootstrap_5_layout.html.twig']
