<?php

namespace App\Controller\Admin;

use App\Entity\Medias;
use App\Entity\Provider;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\FormField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TelephoneField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\DomCrawler\Field\FileFormField;

class ProviderCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Provider::class;
    }

    public function configureFields(string $pageName): iterable
    {
        yield TextField::new('Name');
        yield TextField::new('adress1')->hideOnIndex();
        yield TextField::new('adress2')->hideOnIndex();
        yield NumberField::new('zipcode')->setColumns(2);
        yield TextField::new('city')->setColumns(4);
        yield FormField::addRow();
        yield TextField::new('country')->setColumns(4);
        yield TelephoneField::new('phone')->setColumns(6);
        yield EmailField::new('email')->setColumns(6);
        yield TextField::new('contactFirstName')->setColumns(6);
        yield TextField::new('contactLastName')->setColumns(6);
        yield TelephoneField::new('contactPhone')->setColumns(6);
        yield EmailField::new('contactEmail')->setColumns(6);
        yield TextareaField::new('notes')->hideOnIndex();
        yield AssociationField::new('medias')->hideOnIndex();
        yield BooleanField::new('active');
//        yield ImageField::new('catalog')->setUploadDir('/public/uploads/catalogs');
        yield DateTimeField::new('createdAt')
            ->hideOnForm()->hideOnIndex();
        yield DateTimeField::new('updatedAt')
            ->hideOnForm()->hideOnIndex();


    }

    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions($actions)
            ->add(Crud::PAGE_INDEX, Action::DETAIL);
        // TODO: Change the autogenerated stub
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)
            ->overrideTemplate('crud/detail', '/bundles/EasyAdminBundle/crud/provider_detail.html.twig'); // TODO: Change the autogenerated stub
    }




}
